### ISSUE TITLE
Track rel="nofollow" links differently

### ISSUE THREAD

**Issue by mackaaij** [Yoast/google-analytics-for-wordpress#168]
The plugin currently allows redirected links to be labelled differently, for instance via a /go/ folder.

How about adding an option to label links with rel="nofollow" as well?

Here's an jQuery implementation by somebody who seems to be using the plugin and /go/ already (I left a comment):
http://bradsknutson.com/blog/track-affiliate-link-clicks-with-universal-analytics/

**Comment by jdevalk** [comment]
Not in favor of doing that as the majority of nofollow links is added through `wp_content` filters...

**Comment by mackaaij** [comment]
Thanks for the feedback! I just created this snippet, will try to add it via functions.php somehow later on:

jQuery('a[rel="nofollow"][onclick]:not([class])').attr('onclick', function(i, v){ return v.replace(/(outbound-article-?\w*)/g, '$1-aff'); });

The snippets selects all nofollow links with onclick attributes but strips those with a class (as these tend to be related posts or share buttons). Then replaces the onclick event to append "-aff".

If you have a better idea please do let me know!
