### ISSUE TITLE
File name with a space "Sorting icons.psd"

### ISSUE THREAD

**Issue by waviaei** [Yoast/google-analytics-for-wordpress#208]
There is a file in assets that include a space in its file name "Sorting icons.psd". Is this file meant to be here? If yes, it needs to be renamed, else, to be deleted.

https://github.com/Yoast/google-analytics-for-wordpress/tree/trunk/assets/dependencies/datatables/images

**Comment by omarreiss** [comment]
@waviaei this is an issue with one of our dependencies, please file your issue there -> https://github.com/DataTables/DataTables/tree/master/media/images

**Comment by waviaei** [comment]
@omarreiss Thanks, I have done so.
https://github.com/DataTables/DataTables/issues/533
