### ISSUE TITLE
Error in Description when using Visual Composer

### ISSUE THREAD

**Issue by Peter4576** [Yoast/google-analytics-for-wordpress#219]
Visual Composer is by far the most used page-builder app for WordPress. But Description-field goes mental and takes all the [VC column] tags etc. You should find the most common page-builder apps, and find out what tags they use, so you can remove the tags from automated descriptions. 

Thanks guys!

**Comment by tacoverdo** [comment]
Thanks for reporting this issue. 

Unfortunately the problem isn't entirely clear. So please follow [these guidelines](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report) to improve your [bug report](http://kb.yoast.com/article/180-how-to-write-a-good-bug-report), for example by adding screenshots.

Thank you.
