### ISSUE TITLE
Re-authentication error doesn't dissappear

### ISSUE THREAD

**Issue by Helmi** [Yoast/google-analytics-for-wordpress#236]
Hi,

i downloaded 5.2.6 from github today as the version i had previously installed (5.2.5) didn't work after the last update. Permanently reported errors regarding a WP_SEO_PATH constant and broke my wordpress admin.

Now basically things work again but even though i re-authenticated with google and saved the return code i still get the message i have to re-authenticate.

Any hints?

Frank

**Comment by omarreiss** [comment]
Looks like #260 which was fixed in #263. Closing for now.
