### ISSUE TITLE
Error after updating to version 5.2.6

### ISSUE THREAD

**Issue by danicasati** [Yoast/google-analytics-for-wordpress#237]
After updating, I get a warning on my control panel:
Failed to fetch the new data from Google Analytics. Please reauthenticate on the settings page!

If I reauthenticate, I get this error:
Warning: Invalid argument supplied for foreach() in /web/htdocs/xxxx/home/wp-content/plugins/google-analytics-for-wordpress/admin/class-google-analytics.php on line 183 Warning: array_merge(): Argument #2 is not an array in /web/htdocs/xxxx/home/wp-content/plugins/google-analytics-for-wordpress/admin/class-google-analytics.php on line 188

So dropbox is grey and deactivate, I can't select my profile from list.

Tested in WP 4.0.1 with multisite mode, with Google Chrome 39.

**Comment by omarreiss** [comment]
This has been fixed in the latest release(s). We have a beta available that fixes more issues that are remotely related to this -> https://yoast.com/public-betas-plugins/
