### ISSUE TITLE
'Path for internal links to track as outbound links' not working

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/google-analytics-for-wordpress#256]
Since the last update, the internal links that I had set as outbound links with "Set path for internal links to track as outbound links:" are not working any more.
They are no longer considered as outbound links and therefore not seen in google analytics...

**Comment by JeremyEnglert** [comment]
I'm having an issue with "Outbound Links" being tracked as well. Was this resolved?

**Comment by jeason321** [comment]
I'm not sure what the justification for closing it was.  I was the person that originally reported this over on Wordpress, and the feature still isn't working for me.  No one from the development team bothered to follow up with me and ask if it was fixed or not.

**Comment by tacoverdo** [comment]
This issue was closed because we were unable to reproduce it. 
If you are, please add a [full bug report](http://yoa.st/bugreport) so we can reopen this.

**Comment by jeason321** [comment]
OK, will do when I have a minute.  In the meantime, can you share your test procedure so that I can try to determine if it's the process I'm using to create the links?

Date: Fri, 6 Mar 2015 05:12:10 -0800

**Comment by JeremyEnglert** [comment]
I figured out my issue.

Apparently, I was using an old version of the plugin but because the name of the plugin had changed, I was not getting a notification to update. I removed the old plugin and updated to the new one, everything is now working like a charm.
