### ISSUE TITLE
"Failed to fetch the new data from Google Analytics" notice after authentication

### ISSUE THREAD

**Issue by monbauza** [Yoast/google-analytics-for-wordpress#260]
Two or three days after authenticating with the Google Analytics account, the "Failed to fetch the new data from Google Analytics. Please reauthenticate on the settings page!" notice shows up.
![image1](https://cloud.githubusercontent.com/assets/9658774/5537097/fd512a7a-8a9b-11e4-909f-11e652d58721.png)
The notice dissapears as soon as you go to Analytics -> Settings tab (without reauthenticating again or doing any further action).
![image2](https://cloud.githubusercontent.com/assets/9658774/5537112/524978ac-8a9c-11e4-8d9b-c342c725c90f.png)
WordPress version: 4.1
Plugin version: Google Analytics by Yoast Premium 1.1.7 and Google Analytics by Yoast 5.2.7

**Comment by KirkM** [comment]
Same here on two different websites and this is wide spread b y what I see on the WordPress support page for this plugin. Webhost, browser, adblocking and Do Not Track type extensions (enabled or disabled) and deleting or not deleting browser history browser history <em>appears</em> to have no bearing on the problem.

By what I can tell and I believe what you've stated jdevalk, tracking is actually not affected. At best it's a glitch that doesn't actually affect operation of the plugin. Would that be correct?

**Comment by tacoverdo** [comment]
If you don't want to await the next release, you can test the beta that's available on https://yoast.com/downloads/google-analytics-for-wordpress-5.2.8-beta.zip.
