### ISSUE TITLE
Failed to fetch the new data from Google Analytics. Please reauthenticate on the settings page!

### ISSUE THREAD

**Issue by nkeitht** [Yoast/google-analytics-for-wordpress#269]
I am getting the "Failed to fetch the new data from Google Analytics. Please reauthenticate on the settings page!" message almost daily.

To resolve I need to go to the "General Settings" tab of Yoast Google Analytics and click on the "Re-Authenticate with your Google account" button

**Comment by jdevalk** [comment]
Did you install the latest update we pushed out _today_? :)

**Comment by CarolineGeven** [comment]
Closing this as there was no response and this issue should be fixed in the latest release.
