### ISSUE TITLE
Cannot call overloaded function for non-object

### ISSUE THREAD

**Issue by dhyanan73** [Yoast/google-analytics-for-wordpress#270]
Hi,
my website crashes with error "Cannot call overloaded function for non-object in [...]/wp-content/plugins/google-analytics-for-wordpress/frontend/abstract-class-tracking.php on line 286".

I had to deactivate the plugin to solve the issue.

Plugin version: 5.2.8

**Comment by laserjobs** [comment]
Sounds like an issue with APC, what version of PHP are you using and is APC enabled?

**Comment by dhyanan73** [comment]
@laserjobs Hi, my web server (Bluehost dedicated hosting plan) runs PHP version 5.4.22.

Here is a part of the PHP information page (phpinfo.php) shapshot showing APC configuration:

![apc](https://cloud.githubusercontent.com/assets/10456813/5674155/3b3518bc-97a6-11e4-84c4-39b5ead41cd0.jpg)

**Comment by laserjobs** [comment]
From what I found this error is common to APC. This plugin has had some problems with APC as of late. Is it possible to try disabling APC and see if the error resolves? See if bluehost can help, you might be able to disable it in .htaccess.

**Comment by wilirius** [comment]
I believe this is related to #271 

The plugin is now loading a WordPress file before it is supposed to.

**Comment by dhyanan73** [comment]
@laserjobs thanks for your hint but for me is not possible to disable APC.

@wilirius I agree with you.

**Comment by CarolineGeven** [comment]
There was a beta released 3 days ago that possibly fixes this issue. You can get the beta here: https://yoast.com/public-betas-plugins/

Please let us know if this fixes your issue.

**Comment by dhyanan73** [comment]
@CarolineGeven are you talking about "Google Analytics by Yoast 5.3-beta"?

**Comment by CarolineGeven** [comment]
@dhyanan73 Yes :)

**Comment by CarolineGeven** [comment]
There has been a new update for Google Analytics. Please let us know if the update fixes your issue.

**Comment by dhyanan73** [comment]
Yes, after last update everything works fine. Thanks.
