### ISSUE TITLE
Latest update Google Analytics bugs with Buddypress forum

### ISSUE THREAD

**Issue by CCC-Rikster** [Yoast/google-analytics-for-wordpress#272]
I have updated the latest version of Yoast Google Analytics free plug-in. And my site and attached Forum seamed to work fine, until I wanted to post something new on the forum. I was able to do everything needed to upload a new topic, or a new photo, until I entered "Submit". Then I received the ERROR code that I did not have permission to do this. I heard from other members of the site that they did not have access to the forum at all. After I deactivated the Yoast Google Analytics plug-in everything worked fine again. 
So something is bugging in the new update.
Thank you.

Rik

www.customcarchronicle.com

**Comment by CarolineGeven** [comment]
Thanks for reporting this issue. 
Unfortunately we do not have enough information to reproduce this problem. Please answer the following questions so we can try to figure out what is going on and help us reproduce it.

* What version of WordPress are you running?
* What version of PHP are you running?
* What kind of webserver are you running (Apache, Nginx,IIS)?
* Are you running the latest version of the plugin?
* Do you still have this issue if you switch to the default WordPress theme (*e.g. Twenty Fourteen*) and deactivate all other plugins?

Also, it will help us a lot if you can provide a backtrace of the error encountered. [This gist](https://gist.github.com/jrfnl/5925642) will explain how to enable the backtrace in your website: https://gist.github.com/jrfnl/5925642

Thank you.

**Comment by CarolineGeven** [comment]
Closed as there was no response.
