### ISSUE TITLE
Outbound Links no longer being tracked 

### ISSUE THREAD

**Issue by mriccelli75** [Yoast/google-analytics-for-wordpress#275]
Hello,

I am using the Google Analytics plug in by Yoast. I have the option "Track outbound click & downloads:" checked. It was tracking my outbound clicks in google analytics but all the sudden stopped tracking it. Nothing changed in the code or on the website. Has anyone had this issue of broken outbound link tracking being interrupted?

**Comment by CarolineGeven** [comment]
Unfortunately, this is not a bug, but a support request. We use GitHub exclusively for (well-documented) bug reports, so we cannot help you here.

To receive free support for WordPress SEO we have the following channels:
* [Yoast Knowledge base](http://kb.yoast.com)
* [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

Or if you want personal support via email, you can purchase [WordPress SEO Premium](https://yoast.com/wordpress/plugins/seo-premium/).

Thanks for your understanding.
