### ISSUE TITLE
5.2.8 Logged in session not picked up on frontend

### ISSUE THREAD

**Issue by mbootsman** [Yoast/google-analytics-for-wordpress#276]
I don't know if the title is descriptive enough, but I will try to clarify what is happening.
After updating to 5.2.8 the following happens.

When logged in to the admin, switching to the frontend shows a not-logged-in page. No WP Admin bar, no logged-in body class and the is_user_logged_in() function does not work. Emptying cache (local and server), using different browser, other pc, no change to this behavior.

When deactivating GA for WordPress, all works as expected also after downgrading to 5.2.7

Environnment: WP Multisite with WPMU Domain mapping plugin.

**Comment by rvarbanov** [comment]
Same issue here. Please fix that.
5.2.8 also makes it impossible to preview draft post.

**Comment by omarreiss** [comment]
Should be fixed by #281 
We'll run some tests before release to make sure this issue is actually resolved.
