### ISSUE TITLE
No tabs visible in Admin interface due to jQuery error with Chosen library.

### ISSUE THREAD

**Issue by sfoxe** [Yoast/google-analytics-for-wordpress#279]
Experiencing an issue with Wordpress 4.1, Google Analytics by Yoast v5.2.8, and this is the only plugin installed. Using a bought theme called Espresso by Boxy.

Going to Google Analytics settings page in admin dashboard, and the jQuery tabs are not working, because there is an error that stops javascript continuing. The error is relating to the Chosen library not loading properly.

![chosen_bug_2](https://cloud.githubusercontent.com/assets/931899/5699074/65333292-9a72-11e4-8c71-616194aae3e0.png)
![chosen_bug_1](https://cloud.githubusercontent.com/assets/931899/5699075/65394812-9a72-11e4-8e05-79be55f3b048.png)

**Comment by CarolineGeven** [comment]
Thanks for reporting this issue. 
Unfortunately we do not have enough information to reproduce this problem. Please answer the following questions so we can try to figure out what is going on and help us reproduce it.

* What version of WordPress are you running?
* What version of PHP are you running?
* What kind of webserver are you running (Apache, Nginx,IIS)?
* Are you running the latest version of the plugin?
* Do you still have this issue if you switch to the default WordPress theme (*e.g. Twenty Fourteen*) and deactivate all other plugins?

Also, it will help us a lot if you can provide a backtrace of the error encountered. [This gist](https://gist.github.com/jrfnl/5925642) will explain how to enable the backtrace in your website: https://gist.github.com/jrfnl/5925642

Thank you.

**Comment by sfoxe** [comment]
Thanks for the response. I've been digging further and found the JS Chosen error was a red herring. The actual culprit was the browser extension AdBlockPlus which blocks your plugins stylesheets and javascript from running due to it detecting ad banners as part of the deliverable.

Install AdBlockPlus into either Firefox or Chrome and view the Settings page in your plugin to reproduce the above screenshot symptoms.

**Comment by Tabrisrp** [comment]
Thank you @sfoxe for posting this, I was trying to find for quite some time why I had this issue in my admin, and ABP was indeed the cause

**Comment by CarolineGeven** [comment]
Closed, as AdBlockPlus is the culprit.
