### ISSUE TITLE
Yoast Google Analytics for Wordpress 5.2.7 always forces SSL with universal tracking

### ISSUE THREAD

**Issue by gregscott** [Yoast/google-analytics-for-wordpress#280]
It was suggested in this thread in the Yoast support forum,

https://wordpress.org/support/topic/google-analytics-says-tracking-not-installed-but-it-is-installed-on-my-website?replies=16#post-6423827

that I check in here on github.  At least two of us have run into an issue with Universal Tracking where Google says it's not receiving data.  One helpful respondent looked at the code generated by the plugin and found it wants to force SSL connections.  But my website - and others - are only HTTP websites, not HTTPS.  It seems I'm unable to send Universal Tracking data to Google because my website is an HTTP website.  Google documents no such restriction, so this feels like a plugin bug.  If nothing else, if this is expected behavior, it should at least be documented that way.  But ideally, I should be able to toggle that "force SSL" flag using a GUI in the plugin.  As a workaround, I unchecked the Universal Tracking checkbox in the plugin dashboard and now the website is sending data to Google.  I did check with Google and Google does have my website registered to use Universal Tracking.  

In case github mangles the link to the support thread above, my website is at http://www.infrasupport.com.

thanks

- Greg Scott
  gregscott@infrasupport.com

**Comment by CarolineGeven** [comment]
@jdevalk Could you comment on this?

**Comment by jdevalk** [comment]
We always use SSL because it's always available. Even when your website is HTTP, the tracking data can still be sent over HTTPS.

**Comment by gregscott** [comment]
Hang on a second!  Why are some websites unable to use Universal Tracking?  Just closing the problem report doesn't make the problem disappear.

**Comment by jdevalk** [comment]
The error is lying elsewhere, I'm sorry but there's not much I can do based on the data you've given me so far, the SSL assumption you made was wrong so this is not a valid bug, which is why i'm closing it...

**Comment by DaanMeijer** [comment]
If, for whatever reason, you'd like to turn "forceSSL" off, you can use this filter:

```php
add_filter('yoast-ga-push-array-universal', function($gaq){

	$gaq = array_filter($gaq, function($item){
		return $item != "'set', 'forceSSL', true";
	});
	
	return $gaq;
});
```
