### ISSUE TITLE
Plugin breaks authentication, preview and admin bar on WP-MU sites

### ISSUE THREAD

**Issue by lpar** [Yoast/google-analytics-for-wordpress#289]
Had a problem today where Preview didn't work on my site, and nor did the admin bar on posts.

Turns out google-analytics-for-wordpress was at fault, by including pluggable.php. I'm not a Wordpress expert, but apparently that's a big no-no, and sure enough turning off the plugin fixed the problem.

The two errors caused, in debug mode, are:

Notice: Use of undefined constant AUTH_COOKIE - assumed 'AUTH_COOKIE' 
Notice: Use of undefined constant LOGGED_IN_COOKIE - assumed 'LOGGED_IN_COOKIE' 

The errors break authentication outside of wp-admin.

Relevant stack exchange post:
http://wordpress.stackexchange.com/questions/110620/undefined-constant-error-in-pluggable-php

**Comment by primetel** [comment]
Hi, same problem with my Multisite setup.

**Comment by omarreiss** [comment]
@lpar @primetel  we've released a beta which should fix this problem. We plan to release it as a stable update to wordpress.org next week. You can find it here: https://yoast.com/public-betas-plugins/

Please let us know if this fixes your problem.

**Comment by cliffordp** [comment]
Confirmed same issue. Thanks for the upcoming release fix.

**Comment by danielck** [comment]
We had the same issue in our client's multisite environment and I can confirm that the beta fixes it.

**Comment by omarreiss** [comment]
@danielck @cliffordp thanks for the feedback. We're aiming to release next tuesday.

**Comment by tazotodua** [comment]
The reason:

You are calling `current_user_can` function too early, till actions are loaded. You should put that function in `init` action, for example:

```
add_action('init', 'myfunc');
function myfunc(){
  if (current_user_can('activate_plugins')) { ..........}
}
```
