### ISSUE TITLE
Newest Version breaks admin bar and theme customizer in multisite

### ISSUE THREAD

**Issue by protechig** [Yoast/google-analytics-for-wordpress#296]
During a recent plugin upgrade, I noticed that the admin bar and theme customizer no longer work on any of the individual sites on my multisite install while network activated. I have disabled all other plugins so it is definitely something to do with the new version. I noticed [this thread](https://wordpress.org/support/topic/update-to-528-breaks-admin-bar-on-website) on the wp.org forums which lead me to believe that i'm not the only one experiencing this. I'm on WP Engine if that helps at all.

Please let me know what else you need from me, i'm glad to help.
-Zach

**Comment by prilldev** [comment]
I'm glad someone else is having the same issue as me! I thought it might be related to multi-site, but wasn't sure (I have multi-site as well).

**Comment by CarolineGeven** [comment]
We pushed out an update 2 days ago, please update the plugin. Can you let us know if this solves your issues?

**Comment by prilldev** [comment]
Yes it did. I responded that everything was now good on the issue I wrote
at the github project. Thank you!

**Comment by CarolineGeven** [comment]
Thanks for letting us know! :)

**Comment by protechig** [comment]
@CarolineGeven fixed it for me as well. I keept looking at the form and downloaded the Beta version of the plugin a few days ago. Thanks for getting this fixed!
