### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/google-analytics-for-wordpress#304]
- [x] `Ignore users` on [Line 95 of admin/pages/settings.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/pages/settings.php#L95)
- [x] `Custom code` on [Line 121 of admin/pages/settings.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/pages/settings.php#L121)
- [x] `Save changes` on [Line 145 of admin/pages/settings.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/pages/settings.php#L145)
- [x] `Save changes` on [Line 38 of admin/class-admin-form.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/class-admin-form.php#L38)
- [x] Strings in function `track_download_types` starting on [line 353 on admin/class-admin.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/class-admin.php#L353)
- [x] Strings in function `get_track_full_url` starting on [line 365 on admin/class-admin.php](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/class-admin.php#L365)

**Comment by rubenwoudsma** [comment]
Also some additional untranslated strings:
- [ ] For the 'ignore users' the selectable  roles are not translated although WordPress had translated them;
- [ ] 'Enhanced Link Attribution' on the 'Universal'-tab of the settings section;
- [ ] Tooltip of the 'Enhanced Link Attribution' is not translatable;
- [ ] Dropdown (Events, PageViews) on the advanced section for 'Track downloads';
- [ ] Dropdown for the 'Track whole URL' option;
- [ ] The string on the Extension-page which mentions the text 'Get this extension';

**Comment by andizer** [comment]
@tacoverdo The Enhance Link Attributions are translatable but probably not in de pot file, can you update GlotPress?

**Comment by tacoverdo** [comment]
I'll look into them.

**Comment by tacoverdo** [comment]
.pot file is updated, strings are added to https://translate.yoast.com.
