### ISSUE TITLE
Translations aren't loaded

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/google-analytics-for-wordpress#305]
The translations for Google Analytics by Yoast do not seem to get loaded.

**Comment by Rarst** [comment]
The translation file (testing on ru_RU) is located correctly and determined to be readable, then it bogs down somewhere deep in `MO` class. As far as I got to far.

**Comment by Rarst** [comment]
Re–exporting MO file from https://translate.yoast.com/projects/google-analytics-for-wordpress/ru/default fixes it. Seems like MO files are somehow corrupt.

**Comment by tacoverdo** [comment]
@Rarst We found a difference between files downloaded manually and files downloaded using the grunt download task (https://github.com/markoheijnen/grunt-glotpress).

Example:
```
248 -rw-r-----@ 1 tacoverdo  staff  123971 Jan 30 11:54 wordpress-seo-nl.po (manual)
248 -rw-r--r--  1 tacoverdo  staff  123971 Jan 30 11:53 wordpress-seo-nl_NL.po (grunt)
```
```
192 -rw-r-----@ 1 tacoverdo  staff   95405 Jan 30 11:45 wordpress-seo-nl.mo (manual)
192 -rw-r--r--  1 tacoverdo  staff   98023 Jan 30 11:53 wordpress-seo-nl_NL.mo (grunt)
```

**Comment by omarreiss** [comment]
@Rarst @tacoverdo I found the cause of the issue. It's in the grunt task that downloads the translations. The MO file gets corrupted in the download. Will file a PR to fix that.
