### ISSUE TITLE
Backend crash after update to version 5.3.2.

### ISSUE THREAD

**Issue by swohlert** [Yoast/google-analytics-for-wordpress#318]
Problem occurred on two of my websites I have tried.

I install the update, and the backend just becomes a blank. When I remove the plugin using FTP the backend starts working again.

I can replicate the bug by reinstalling the plugin. If needed I can provide access to the backend and FTP.

I use the Genesis Framework with Education Pro child theme.
Hosted on Synthesis.

Active plugins:
MPM - Mollie Payment Module	 	door Mollie – 1.3.1
Google Analytics eCommerce tracking addon for Yoast GA	 	door Team Yoast – 3.0.2
Genesis Connect for WooCommerce	 	door StudioPress – 0.9.8
Genesis Responsive Slider	 	door StudioPress – 0.9.2
Genesis Simple Sidebars	 	door Nathan Rice – 2.0.1
Ninja Forms	 	door De WP Ninjas – 2.8.13
Regenerate Thumbnails	 	door Viper007Bond – 2.2.4
Responsive Lightbox	 	door dFactory – 1.4.10
W3 Total Cache	 	door Frederick Townes – 0.9.4.1
Woocomerce Advanced Product Labels	 	door Jeroen Sormani – 1.0.0
WooCommerce Colors	 	door WooThemes – 1.0.3
WooCommerce TM Extra Product Options	 	door themecomplete – 3.0.7
WooCommerce	 	door WooThemes – 2.3.4
WooThemes Helper	 	door WooThemes – 1.4.1
WordPress HTTPS	 	door Mike Ems – 3.3.6
WordPress Importeerder	 	door wordpressdotorg – 0.6.1
WordPress SEO-Premium	 	door Team Yoast – 1.5.2
WP Customer Reviews	 	door Go Web Solutions – 2.4.8
Local SEO for WordPress SEO by Yoast	 	door Team Yoast and Arjan Snaterse – 1.3.4.1
Yoast WooCommerce SEO	 	door Team Yoast – 1.1.5
MailPoet Newsletters	 	door MailPoet – 2.6.15

**Comment by tacoverdo** [comment]
Can you please add the content of your server or error log here? Blank pages in WordPress always mean there's been a fatal error. Having the exact error will help us a great deal in solving the problem.

Thanks in advance!

**Comment by swohlert** [comment]
2/18/2015 12:52:23 PM - www: PHP Fatal error: Class 'Yoast_GA_Frontend' not found in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/googleanalytics.php on line 52

2/18/2015 12:52:23 PM - www: PHP Warning: include(): Failed opening '/var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/frontend/class-frontend.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/vendor/composer/ClassLoader52.php on line 186

2/18/2015 12:52:23 PM - www: PHP Warning: include(/var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/frontend/class-frontend.php): failed to open stream: No such file or directory in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/vendor/composer/ClassLoader52.php on line 186

**Comment by Rarst** [comment]
Could you please verify that said file (`/wp-content/plugins/google-analytics-for-wordpress/frontend/class-frontend.php`) exists in file system on your server? I had downloaded clean copy of 5.3.2 from plugin repository and it both contains said file and works fine for me.

**Comment by swohlert** [comment]
File exists on the server. Just reinstalled it and the backend has crashed again.

Latest server log on time of installing:

2/18/2015 12:52:23 PM - www: PHP Fatal error: Class 'Yoast_GA_Frontend' not found in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/googleanalytics.php on line 52

2/18/2015 12:52:23 PM - www: PHP Warning: include(): Failed opening '/var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/frontend/class-frontend.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/vendor/composer/ClassLoader52.php on line 186

2/18/2015 12:52:23 PM - www: PHP Warning: include(/var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/frontend/class-frontend.php): failed to open stream: No such file or directory in /var/www/kozijnen-inkoop.nl/wp-content/plugins/google-analytics-for-wordpress/vendor/composer/ClassLoader52.php on line 186

**Comment by Rarst** [comment]
What are the permissions on the file? If you could please inquire with your hosting support are there any security measures in place that would prevent PHP file from being included?

**Comment by swohlert** [comment]
I'll check with Synthesis, but I know you're also hosting with Synthesis so that shouldn't be the problem.

**Comment by swohlert** [comment]
I've checked with Synthesis and they reset all permissions at the server level. Removed and installed again but problem remains.

**Comment by Rarst** [comment]
Hm... This is highly peculiar. I would suggest trying to:

1. Install earlier plugin version
2. Run latest version with other plugins disabled

**Comment by swohlert** [comment]
Where can I find the previous version?

**Comment by Rarst** [comment]
Earlier versions are always available at https://wordpress.org/plugins/google-analytics-for-wordpress/developers/ , for example https://downloads.wordpress.org/plugin/google-analytics-for-wordpress.5.3.1.zip

**Comment by swohlert** [comment]
I have installed the version and will be trying that tomorrow when I have a full workday to try it. Thanks for the help so far and I'll keep you updated.

**Comment by Rarst** [comment]
Do you mean that 5.3.1 works without exhibiting the issue (or you just left it disabled)? That might give us something to look into in the meantime.

**Comment by swohlert** [comment]
Version 5.3.1 works just fine. I only have it when I use 5.3.2

**Comment by stevengliebe** [comment]
There are details from others experiencing the same issue on the WordPress support forum: https://wordpress.org/support/topic/latest-update-to-ga-ecommerce-broke-administration-panel

It seems like 5.3.2 introduced a change that causes a fatal error when the eCommerce add-on is active. Rolling back to 5.3.1 removed the issue for me.

**Comment by ctalkington** [comment]
@Rarst seeing this also, same error

**Comment by jamesdoylephoto** [comment]
I'm having exactly the same problem. I'm with Synthesis using Genesis Framework and the 5.3.2 version of the plugin just gives me a blank screen. If I install version 5.3.1 of the plugin it works fine.

**Comment by Rarst** [comment]
I am not confident if that is same issue or two distinct ones (reported here and reported on dot org forums).

The issue from forums with `class-license-manager.php` should be fixed in ga-ecommerce 3.0.3 release. However issues with `class-frontend.php` might be different.

Could OP please try GA 5.3.2 + ga-ecommerce 3.0.3 combination?

**Comment by swohlert** [comment]
Steps I followed:
- Update GA eCommerce addon to 3.0.3 - Everything works
- Update GA by Yoast to 5.3.2 - Everything works.

Seems like the bug was caused with the combination of GA eCommerce and GA by Yoast.
Thanks for the fix.

**Comment by Rarst** [comment]
Good to hear, thank you for helping look into it. :)

**Comment by secretstache** [comment]
Where can I find a copy of GA eCommerce 3.0.3? I do not see an update available within WP

**Comment by fracasula** [comment]
Still issue here and I'm not using the GA eCommerce plugin. Reverting to 5.3.1...
I'm using Wordpress 4.1.1 on a RedHat system.
