### ISSUE TITLE
Default for 'ignore users' should be Administrator, if anything

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/google-analytics-for-wordpress#361]
Current default is `Editor`. In my opinion this makes less sense than excluding administrators by default, and I'm not even sure we should exclude any user role from tracking by default. 

@jdevalk how do you feel about this?

**Comment by jdevalk** [comment]
Exclude administrators AND editors by default. It makes sense to not want to clutter your stats.

**Comment by ctalkington** [comment]
glad to see this updated. though i wish there was a way for the site overlay view to still work when these are excluded.
