### ISSUE TITLE
Upgrading via git troubles on server

### ISSUE THREAD

**Issue by mnelson4** [Yoast/google-analytics-for-wordpress#383]
We have a staging server and a live server of eventsmart.com, both using this plugin and both version-controlled using git.
We upgraded on the staging server first to verify everything worked correctly, and then committed the change, and pushed it to the live server. The live server then blew up with errors like this: https://docs.google.com/file/d/0B2KCao4zFjaxR1NFekppUGMwVW8/edit?usp=drivesdk (except this error is actually from a localhost copy of the same eventsmart server, hence why this error has local filepaths in it).
We realized that we had .gitignore setup to ignore any folders named "cache", so git was ignoring google-analytics-for-wordpress/vendor/yoast/api-libs/google/cache, and causing this issue. But I have two main questions:

1. Usually "Cache" files are specific to the server (eg they may cache filepaths that apply to our staging server but wouldn't apply to our live server) and SHOULD be ignored by git. Is that also right for these "cache" files, that they should they be ignored by git?

2. If so, the plugin should be verifying that those cache files exist, and if not, it should re-generate them right? If it doesn't check on every request, at very least it should check when it detects the plugin has been upgraded or reactivated.

**Comment by Rarst** [comment]
That folder contains actual code, related to caching functionality. It's not something generated or disposable.

See https://github.com/Yoast/api-libs/issues/21

**Comment by mnelson4** [comment]
right sorry I missed that issue; ya this is a duplicate of it
