### ISSUE TITLE
Updating to 5.4.2 Crashes Blog

### ISSUE THREAD

**Issue by coleHafner** [Yoast/google-analytics-for-wordpress#387]
I just updated to version 5.4.2 and I get the following error: "Fatal error: Class 'Yoast_GA_Frontend' not found in D:\Hosting\2826016\html\wp-content\plugins\google-analytics-for-wordpress\googleanalytics.php on line 59"

Wordpress Version: 4.2.1
Hosting: GoDaddy Economy (Windows)
Update Method: Manual (ie moved directory into wp-content/plugins)
Other: I'm using a child theme, that could have something to do with it.

**Comment by michaelbragg** [comment]
I've had the same issue when installing the plugin on a fresh WordPress install.

The plugin is being pulled in via `git submodule` from this repo with a hash for the git tag 5.4.2.

Looking at the info in issue #2382. The `./vendor` folder is missing from the git repo. It is also missing when downloading the plugin from the [releases](https://github.com/Yoast/google-analytics-for-wordpress/releases) page.

It is however present in the download from wordpress.org.

When uploading the `./vendor` folder from the wordpress.org download the plugin works as expected.

**Comment by Rarst** [comment]
The Git repo now represents development sources and isn't ready to be used as is. Vendor directory is built with Composer, unless you are getting ready-made release from official repository, as you have noticed.

Please see the current [Installation](https://github.com/Yoast/google-analytics-for-wordpress#installation) instructions.

**Comment by npfedwards** [comment]
We also use git submodules, and attempting to run composer update/install within the plugin errors.

We'd rather not have to hold your entire plugin in git, and as you are working in git adding a submodule makes sense.

Basically, I think what I (and @michaelbragg) need is an installation method for the production tag via git or maybe composer.

Thanks

**Comment by michaelbragg** [comment]
Our solution was to include the whole plugin for the couple of projects we couldn't alter the deploy process. 

For new, and those that we could change, we moved over to composer and wpackagist with pulling the odd private project from external GIT repos. 

This plugin works seamlessly with both.  

------
Michael Bragg

**Comment by Rarst** [comment]
Composer should work just fine. :) It's natively on Packagist too, not just wpackagist.
