### ISSUE TITLE
Yoast doesn't escape special characters in outbount link tracking

### ISSUE THREAD

**Issue by jamalneufeld** [Yoast/google-analytics-for-wordpress#389]
Yoast isn't escaping special characters in the title when adding tracking to outbound links causing the tracking function to fail.

For example my link is 
`<a...>Lorem's Ipsum</a>`
and Yoast turns it into 
`<a ... onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.loremsipsum.com/', 'Lorem's Ipsum']);" ... >Lorem's Ipsum</a>`

but it should escape the apostrophe: `'Lorem\'s Ipsum'` or else javascript barfs and doesn't track it.

**Comment by Rarst** [comment]
Can't reproduce, this is what I am seeing in source `onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.loremsipsum.com/', 'Lorem&#8217;s Ipsum']);"` if I include the link in post content. The apostrophe is converted to character entity.
