### ISSUE TITLE
Signed-in users not ignored if signed in on one browser and viewing website on another

### ISSUE THREAD

**Issue by eleanorcave** [Yoast/google-analytics-for-wordpress#394]
Hi,
I am an administrator for a website (www.stamaryschildcare.org.nz) using WordPress v 4.2.2, Suffusion theme v 4.4.7 and Google Analytics by Yoast v 5.4.2. 

I have just realised that my favourite trick of viewing the website as a 'non-logged in' user in Firefox and logging in and editing via Chrome may be stuffing up my Google Analytics reports when I am using your plugin. I have looked at the source code in Firefox when I am signed into the website in Chrome and I am not excluded. Is there anything you/|I can do to remedy this?

Thanks
Eleanor

**Comment by Rarst** [comment]
There is no way for plugin to know you want to be logged out, but still opt out of analytics too.

If you have static IP address you could configure Google Analytics to always exclude it from stats.

**Comment by lkraav** [comment]
https://tools.google.com/dlpage/gaoptout

**Comment by Rarst** [comment]
@lkraav cheers! :)

**Comment by eleanorcave** [comment]
Thanks for all your help. We have a dynamic IP so will use https://tools.google.com/dlpage/gaoptout.
