### ISSUE TITLE
Visual Composer images not recognized

### ISSUE THREAD

**Issue by katecinch** [Yoast/google-analytics-for-wordpress#407]
I am using Visual Composer with my wordpress theme (self hosted), and have inserted various images via this tool, but the Yoast plug-in is telling me there are no images on my pages, and my SEO analysis is marked down because of this. Any idea how to how to fix?

**Comment by Rarst** [comment]
Did you mean to report this for SEO plugin, not the Google Analytics one? :)

https://github.com/Yoast/wordpress-seo/issues

**Comment by katecinch** [comment]
My apologies, yes the SEO plugin, not the Analytics one! (brain overloaded, sorry!) :-)

**Comment by Rarst** [comment]
Would you please open the issue there accordingly? :)

**Comment by Rarst** [comment]
See https://github.com/Yoast/wordpress-seo/issues/2733
