### ISSUE TITLE
Reports not showing after update to Wordpress 4.3

### ISSUE THREAD

**Issue by Johnnieq** [Yoast/google-analytics-for-wordpress#418]
Overview still viewable but no reports after updating to Wordpress 4.3. Tested on 2 sites with same result.

**Comment by Rarst** [comment]
Can reproduce.

JS error (multiple instances) :

> Uncaught TypeError: Cannot use 'in' operator to search for 'length' in

Coming from `c.parse_response @ yoast_ga_admin_dashboard.min.js?ver=5.4.5:1`

**Comment by tacoverdo** [comment]
For reference and testing.

**Example of current (broken) output**
![cm3w7yjwuaa8snf](https://cloud.githubusercontent.com/assets/5147598/9402800/209644c2-47e1-11e5-8524-fedd107508db.jpg)

**Example of correct output**
![yoast_google_analytics__dashboard_ _wp41_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/9403175/d9019338-47e4-11e5-9854-b73d11cb8ca7.png)
