### ISSUE TITLE
Fatal Error on activating plugin on Wordpress network level 

### ISSUE THREAD

**Issue by johnnytrinh** [Yoast/google-analytics-for-wordpress#428]
Having an issue with the latest version of plugin. After downloading I receive the following error:

Plugin could not be activated because it triggered a fatal error.

Fatal error: Class 'Yoast_GA_Admin' not found in /Users/name/project-folder/project/wp-content/plugins/google-analytics-for-wordpress/googleanalytics.php on line 53

**Comment by Rarst** [comment]
How precisely had you installed the plugin?

**Comment by johnnytrinh** [comment]
@Rarst I have added it manually into my solution from unzipping from the release folder from the Github repo. (not downloading from wordpress plugins with admin)

**Comment by Rarst** [comment]
Github now contains the development source, is needs to be further built with Composer into usable plugin, see [Installation](https://github.com/Yoast/google-analytics-for-wordpress#installation) (or just fetch a ready-made release from official repository).
